### ISSUE TITLE
CMakeLists.txt file missing in libfixmath

### ISSUE THREAD

**Issue by nevat** [ijacquez/libyaul#1]
CMake Error in CMakeLists.txt:
  The source directory

    .../libyaul-master/libfixmath

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!

**Comment by ijacquez** [comment]
Before building, can you do:

    git submodule init
    git submodule update -f

**Comment by nevat** [comment]
Perfect, now compiles correctly. Thanks for your support.
