### ISSUE TITLE
[Feature] in vdp2_init, add struct parameter to set resolution

### ISSUE THREAD

**Issue by shazz** [ijacquez/libyaul#12]
Would be nice to add an optional parameter to resolution (320x224, 320x240, hires,...)

**Comment by ijacquez** [comment]
I plan to have a separate function for this. This is for when a user wants to change resolutions at any other time.

**Comment by shazz** [comment]
that's fine.

**Comment by ijacquez** [comment]
I refactored to set resolution: `vdp2_tvmd_display_res_set()`.
