### ISSUE TITLE
Wrong masks in vdp2_scrn_ls_set.c

### ISSUE THREAD

**Issue by shazz** [ijacquez/libyaul#20]
the masks are wrong:
```
 case SCRN_NBG0:
                vdp2_state.buffered_regs.scrctl &= 0xFFF9;
                ...
        case SCRN_NBG1:
                vdp2_state.buffered_regs.scrctl &= 0xF9FD;
                ...
                break;
```

for NBG0 should be: `vdp2_state.buffered_regs.scrctl &= 0x3F01`; to mask only NBG0 linescroll features
for NBG1 should be: `vdp2_state.buffered_regs.scrctl &= 0x013F; ` to mask only NBG1 linescroll features

**Comment by ijacquez** [comment]
Good catch.
