### ISSUE TITLE
[bug] bad copy paste in  libyaul/libyaul/scu/bus/b/vdp2/vdp2_scrn_scroll_y_set.c

### ISSUE THREAD

**Issue by shazz** [ijacquez/libyaul#23]
```
void
vdp2_scrn_scroll_x_set(uint8_t scrn, fix16_t scroll)
{
```
x instead of y

**Comment by ijacquez** [comment]
Fixed with [5ddbd9b939b2836892ad7474ad3703f63b040d24](https://github.com/ijacquez/libyaul/commit/5ddbd9b939b2836892ad7474ad3703f63b040d24)
