### ISSUE TITLE
Examples don't match library

### ISSUE THREAD

**Issue by ChillyWillyGuru** [ijacquez/libyaul#27]
While I was able to compile the toolchain and libs, the examples seem to not match in areas. For example, dark_blue.c line 87 is
`        vdp2_scrn_back_screen_color_set(VRAM_ADDR_4MBIT(2, 0x01FFFE), 0x9C00);`

which gives an error for not being a color_rgb555_t value. So I changed it to
`        vdp2_scrn_back_screen_color_set(VRAM_ADDR_4MBIT(2, 0x01FFFE),
		    COLOR_RGB555(0, 0, 7));`
which compiles fine. Worse, the next error is in object_world.c line 258, which is
`        vdp2_scrn_scv_x_set(SCRN_NBG1, THIS_PRIVATE_DATA(object_world, move),
            0);`
which apparently no longer exists. I couldn't find anything remotely similar in the vdp2 scrn library. There are some errors with defines right after that which are gone, too.

`object_world.c:270:25: error: implicit declaration of function 'VDP2_PN_CONFIG_2_CHARACTER_NUMBER' [-Werror=implicit-function-declaration]
object_world.c:271:29: error: implicit declaration of function 'VDP2_PN_CONFIG_1_PALETTE_NUMBER' [-Werror=implicit-function-declaration]
object_world.c:300:25: error: implicit declaration of function 'VDP2_PN_CONFIG_1_CHARACTER_NUMBER' [-Werror=implicit-function-declaration]`

None of those constants exist that I can find. I suspect that the vdp2 scrn library changed, but the updates you made to the examples didn't get committed.

**Comment by ijacquez** [comment]
This example is set to be removed as it's extremely out of date.

See `game-blue` for a working version. It's a complete rewrite.

Other examples may or may not compile as there were many changes to made to the library.

**Comment by ijacquez** [comment]
To be specific, the `game-blue` branch.

**Comment by ChillyWillyGuru** [comment]
Okay, thanks. I'll try that. I was just coming back to note that dark-blue had a bunch of #include <fixmath.h> lines that should now be #include <math.h> to work. :)

**Comment by ChillyWillyGuru** [comment]
Okay, the game_blue compiles, but I did have to change one line in the makefile
`	tiled --export-map "Json files (*.json)" $< $@`
to
`	echo tiled --export-map "Json files (*.json)" $< $@`

Without the echo, the command fails, given an unknown format error. Note that I'm using the tiled in the Ubuntu 16.04 repo, which is still 0.14.2. It might be that 0.16.1 handles this, but 0.16.1 isn't available for linux yet. They just have Windows, OSX, and source.

**Comment by ijacquez** [comment]
If you have Windows or Mac OS, open the `.tmx` files and export them into the same directory as `.json` files.

You need the map data.

**Comment by ChillyWillyGuru** [comment]
Scratch that above comment - it's not really doing the export. The echo just makes it echo the line. Sorry about that. I'll try to figure out what's what.

**Comment by ijacquez** [comment]
I believe I'm on Ubuntu 15.x and I don't get any errors.

**Comment by ChillyWillyGuru** [comment]
Okay, I tried the line
`	tiled --export-map $< $@`
and it does the conversion. Then tmx2map fails with this message

tools/tmx2map
Processing `worlds/test.json'
Camera speed: 1.0000000
Start delay: 2s
  Blue		#015 @ ( 36,144) cell: [  2,  8]
    1. Coin		#001 @ (108,172) cell: [  6, 11] value: 100 points
    2. Coin		#005 @ (108,156) cell: [  6, 10] value: 100 points
    3. Coin		#017 @ (108,140) cell: [  6,  9] value: 100 points
    4. Coin		#018 @ (108,124) cell: [  6,  8] value: 100 points
    5. Coin		#053 @ (108, 60) cell: [  6,  4] value: 100 points
    6. Coin		#055 @ (108, 76) cell: [  6,  5] value: 100 points
    7. Coin		#063 @ (108, 92) cell: [  6,  6] value: 100 points
    8. Coin		#064 @ (108,108) cell: [  6,  7] value: 100 points
    9. Coin		#004 @ (124,172) cell: [  7, 11] value: 100 points
   10. Coin		#006 @ (124,156) cell: [  7, 10] value: 100 points
   11. Coin		#020 @ (124,124) cell: [  7,  8] value: 100 points
   12. Coin		#021 @ (124,140) cell: [  7,  9] value: 100 points
   13. Coin		#056 @ (124, 60) cell: [  7,  4] value: 100 points
   14. Coin		#057 @ (124, 92) cell: [  7,  6] value: 100 points
   15. Coin		#059 @ (124,108) cell: [  7,  7] value: 100 points
   16. Coin		#060 @ (124, 76) cell: [  7,  5] value: 100 points
   17. Coin		#092 @ (124, 28) cell: [  7,  2] value: 100 points
   18. Coin		#094 @ (124, 44) cell: [  7,  3] value: 100 points
   19. Coin		#011 @ (140,172) cell: [  8, 11] value: 100 points
   20. Coin		#014 @ (140,156) cell: [  8, 10] value: 100 points
   21. Coin		#019 @ (140,124) cell: [  8,  8] value: 100 points
   22. Coin		#022 @ (140,140) cell: [  8,  9] value: 100 points
   23. Coin		#054 @ (140, 76) cell: [  8,  5] value: 100 points
   24. Coin		#058 @ (140, 92) cell: [  8,  6] value: 100 points
   25. Coin		#061 @ (140,108) cell: [  8,  7] value: 100 points
   26. Coin		#062 @ (140, 60) cell: [  8,  4] value: 100 points
   27. Coin		#093 @ (140, 44) cell: [  8,  3] value: 100 points
   28. Coin		#095 @ (140, 28) cell: [  8,  2] value: 100 points
   29. Coin		#066 @ (156,140) cell: [  9,  9] value: 100 points
   30. Coin		#072 @ (156,156) cell: [  9, 10] value: 100 points
   31. Coin		#073 @ (156,172) cell: [  9, 11] value: 100 points
   32. Coin		#096 @ (156,188) cell: [  9, 12] value: 100 points
   33. Coin		#067 @ (172,156) cell: [ 10, 10] value: 100 points
   34. Coin		#069 @ (172,172) cell: [ 10, 11] value: 100 points
   35. Coin		#070 @ (172,140) cell: [ 10,  9] value: 100 points
   36. Coin		#065 @ (188,140) cell: [ 11,  9] value: 100 points
   37. Coin		#068 @ (188,156) cell: [ 11, 10] value: 100 points
   38. Coin		#071 @ (188,172) cell: [ 11, 11] value: 100 points
   39. Coin		#080 @ (188, 92) cell: [ 11,  6] value: 100 points
   40. Coin		#082 @ (188, 76) cell: [ 11,  5] value: 100 points
   41. Coin		#083 @ (188,124) cell: [ 11,  8] value: 100 points
   42. Coin		#086 @ (188, 60) cell: [ 11,  4] value: 100 points
   43. Coin		#089 @ (188,108) cell: [ 11,  7] value: 100 points
   44. Coin		#074 @ (204,172) cell: [ 12, 11] value: 100 points
   45. Coin		#075 @ (204,140) cell: [ 12,  9] value: 100 points
   46. Coin		#076 @ (204,156) cell: [ 12, 10] value: 100 points
   47. Coin		#077 @ (204, 60) cell: [ 12,  4] value: 100 points
   48. Coin		#081 @ (204, 76) cell: [ 12,  5] value: 100 points
   49. Coin		#084 @ (204, 92) cell: [ 12,  6] value: 100 points
   50. Coin		#085 @ (204,124) cell: [ 12,  8] value: 100 points
   51. Coin		#091 @ (204,108) cell: [ 12,  7] value: 100 points
    1. Collider	#030 @ (  0,  0) cell: [  0,  0] W/H: (320, 16)
    2. Collider	#033 @ ( 16, 16) cell: [  1,  1] W/H: ( 96, 32)
    3. Collider	#034 @ (160, 16) cell: [ 10,  1] W/H: ( 16,112)
    4. Trigger	#028 @ (304,  0) cell: [ 19,  0] W/H: ( 16,224)
  --------------+
  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "tools/tmx2map", line 271, in <module>
    process(json_data)
  File "tools/tmx2map", line 243, in process
    cell_no = max(0, map_data[cell_x + (cell_y * map_width)] - 1)
TypeError: unsupported operand type(s) for -: 'unicode' and 'int'

Makefile:66: recipe for target 'worlds/test.json' failed
make: *** [worlds/test.json] Error 1
rm worlds/test.json

**Comment by ijacquez** [comment]
That's a bug. The output format should be uncompressed, none-base64. Go to map properties and see if the option to set the map data is there. Ultimately, in the `.json` file, the actual map data should be integers.

**Comment by ChillyWillyGuru** [comment]
Here's the json file created: http://pastebin.com/76ND0B9Y

**Comment by ChillyWillyGuru** [comment]
That's part of test.tmx:

` <layer name="World" width="20" height="14">
  <data encoding="base64">
   AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAA==
  </data>
 </layer>`

**Comment by ChillyWillyGuru** [comment]
From what I read online, you need to load the TMX into tiled, set it to CVS or XML mode (non-base64) and save it. The tmx files are all in base64 mode right now, so when they are converted to json, they remain in base64 mode.

**Comment by ChillyWillyGuru** [comment]
I tried it on test.tmx and it works! I changed the mode from base64 to cvs and saved, and now it fails (for the same reason) on test2.json. I'll change all three tmx files and try again.

**Comment by ChillyWillyGuru** [comment]
Okay, that ran through just fine. So resaving the tmx files with the mode changed from base64 to cvs, and that one change to the tiled line in the makefile makes it work.

**Comment by ijacquez** [comment]
Thanks for the help. I'll have `tmx2map` deal with base64 just in case.

Note, the "game" is still being worked on.

Closing. If you have other issues, open a new issue :)

Thanks again!
