### ISSUE TITLE
Cosmetic issue with build-script

### ISSUE THREAD

**Issue by ChillyWillyGuru** [ijacquez/libyaul#29]
I was rebuilding the latest from scratch and noticed this line
`Set INSTALL_ROOT variable (in ../yaul.env) to '/opt/toolchains/Saturn/sh-elf'`

That's wrong - INSTALL_ROOT shouldn't have '/sh-elf' on the end or it will fail to build the library. It's not a big deal since the yaul.env.in makes no mention of that, but the message should be consistent to avoid confusion.

**Comment by ijacquez** [comment]
Thanks for the heads up! I ended up removing the line. The main `README.markdown` tells you the next step to take, so the message itself was rather redundant.
