### ISSUE TITLE
USB Cart no longer supported?

### ISSUE THREAD

**Issue by ChillyWillyGuru** [ijacquez/libyaul#33]
While compiling the library, I had the option for the USB cart set, but it built yaul.h with the following

`#if HAVE_DEV_CARTRIDGE != 0`
`#error "Invalid HAVE_DEV_CARTRIDGE value"`
`#endif`

**Comment by ijacquez** [comment]
Yeah, that's wrong. I think I changed it last night. It should check for values 0, 1, and 2.

I'll fix in a few. In the meantime, remove it.

Thanks.

**Comment by ChillyWillyGuru** [comment]
No problem. I thought that was probably the case... just edits in progress and not finished yet. :)
