### ISSUE TITLE
Compiler build system upgrade.

### ISSUE THREAD

**Issue by GravisZro** [ijacquez/libyaul#35]
I wish to improve your compiler build system because I would like to make libyaul into the centerpiece of a Saturn SDK.  I made the [build system for a Dreamcast SDK](https://github.com/DreamcastSDK/build) and wish to similarly update your system.

The end result would be an SDK that can easily be built without needing to read any instructions about how to do it while leaving powerful options for those who do.

**Comment by ijacquez** [comment]
Interesting project. I wasn't aware of this.

I don't see much a difference between with what I [have written](https://github.com/ijacquez/libyaul/tree/master/build-scripts) and the build system. Is it that it does more steps automagically? Would it also handle building the M68K cross-compiler?

Would you plan to integrate [this](https://github.com/ijacquez/libyaul/tree/master/build-scripts) with your build system?

**Comment by GravisZro** [comment]
My script is a single standard POSIX shell script that detects which tools (supports multiple platforms) you have installed automatically downloads the required files to build gcc.  The DC version builds both SH4 and ARMv4 toolchains (bootstrapping newlib and all) as well as a few key libraries.  It will also install and uninstall them in your system so that you never have to run any environment configuration script.  This enables users to use it with any IDE they want without hackery.  There are also advanced options when building.  Adapting it for Saturn won't be a challenge.

You will understand if you clone the "build" repo and run the setup script file.  There is even a -h/--help option for it.

**Comment by ijacquez** [comment]
I'll clone it and give it a shot.

So the end result would be to incorporate your build system in libyaul? Effectively replacing `build-scripts/`? Have you had any luck with convincing the KallistiOS devs?

**Comment by GravisZro** [comment]
The end result would separate libyaul from the build system.  The only thing libyaul would have is a single custom makefile.  The specs files and linker scripts would be installed with the compiler so that they were used by default.  This is the same thing I did for KOS, though it looks like your makefile for yaul is in good shape.

The current KOS maintainer has refused all efforts to improve/modernize his convoluted build system despite frequent requests to make the toolchain and libraries install independently of the source.   Seriously, it took weeks to finally untangle it correctly because of nested custom makefiles, scripts and utilities that all used relative paths to reference each other. This is why I was forced to fork KOS.

**Comment by ijacquez** [comment]
Apologies for the late response.

I believe my build system already does this. It installs itself to wherever the tool-chain was installed to. Though, it's been quite a while since I've last touched the files.

If you immediately know of any clear shortcomings in my build system, let me know via issues, or via pull requests.

Since I genuinely don't have much time (working on other projects) to work on libyaul, I would suggest to fork and when I do have time, I could either bring the entire system over, or parts of it.

Thanks for all the help, @GravisZro.

**Comment by ijacquez** [comment]
Closing. I'll reopen if needed.
