### ISSUE TITLE
FIX16_VECTOR4_INITIALIZER lacks {}

### ISSUE THREAD

**Issue by razor85** [ijacquez/libyaul#58]
As title says, `FIX16_VECTOR4_INITIALIZER` lacks an `{}` to initialize objects.

**Comment by ijacquez** [comment]
#define FIX16_VECTOR4_INITIALIZER(x, y, z, w)                              \
    {                                                                          \
            F16(x),                                                            \
            F16(y),                                                            \
            F16(z),                                                            \
            F16(w),                                                            \
    }

That's how it's defined. How are you using the macro?

`fix16_vector4 a = FIX16_VECTOR4_INITIALIZER(1.0f, 1.0f, 1.0f, 1.0f);`

This could conflict with the hundred different ways you can initialize in C++11 and up.

**Comment by razor85** [comment]
I think what I meant back then (Can't remember exactly) was to get fix16_vector4 a = {1, 2, 3, 4};

**Comment by ijacquez** [comment]
Closing. This will be addressed in the math cleanup.
