### ISSUE TITLE
ssload doesn't work with USB Cart Dev

### ISSUE THREAD

**Issue by shazz** [ijacquez/libyaul#7]
Currently I'm using ftx as a woarkaround

**Comment by ijacquez** [comment]
Solution is to either debug `ssload` D2XX drivers or reimplement with libftdi.

**Comment by ijacquez** [comment]
[Implemented support](https://github.com/ijacquez/libyaul/commit/93be441ec8a3ec323aac929b7455c97bf0ac5e1b). Can you please test and verify that it works? `make clean` followed by `make` should be enough provided you have *libFTDI* installed.

**Comment by shazz** [comment]
it compiles now... and works !

**Comment by ijacquez** [comment]
Thanks for the update. Closing. Open a new issue if a problem occurs.
