### ISSUE TITLE
Can't Make Examples

### ISSUE THREAD

**Issue by JonSTGaming** [ijacquez/libyaul#71]
I can't make the examples after using the installer (on windows 10 64-bit).
Everytime I do i get the error of `Makefile:51: *** Undefined YAUL_INSTALL_ROOT (install root directory).  Stop.` so I opened it up in notepad, but couldn't find where to put my install location.

**Comment by ijacquez** [comment]
Sorry for the late response. I didn't get a notification.

Can you please tell me what steps you are taking to build examples? If you used the installer, all you need to do is open `mingw64.exe` from `C:\yaul\` and go to `/opt/libyaul/examples/`, choose an example, and type `make clean; make`.

**Comment by JonSTGaming** [comment]
alright thanks, i think it worked

**Comment by ijacquez** [comment]
If you have any bugs to report, create a new issue. Thanks.

Closing.
