### ISSUE TITLE
DMA Indirect mode transfer freezes the Saturn

### ISSUE THREAD

**Issue by shazz** [ijacquez/libyaul#8]
Using libyaul to transfer blocks of data using the indirect mode freezes the Saturn

**Comment by shazz** [comment]
While re-reading again the SCU manual, I found a possible reason:

During DMA activation, any write to a DMA registers (DxMD, DxAD) will hang the system: so maybe checking the DSTA register before any write could be useful

**Comment by ijacquez** [comment]
Only those two? Or any writable SCU DMA register? What page are you looking at?

**Comment by shazz** [comment]
SCU specification 23 from tech notes (p29):
"Write to register of corresponding level is prohibited during DMA activation"

The selection register for DMA mode, address update, and activation factor (*1) and the
DMA set register (2) cannot be rewritten during DMA activation of the corresponding level.
If either of these registers is rewritten, the system hangs.

*1 Selection register for DMA mode, address update, and activation factor
Address level 0 25FE0014H, level 1 25FE0034H, level 2 25FE0054H
*2 DMA set register
Address level 0 25FE000CH, level 1 25FE002CH, level 2 25FE004CH

**Comment by shazz** [comment]
So in fact, it did not work because the DMA end code was not well set.
Could you just add a check in the sanitizer : if the 31th bit ofd the last src of the table is not set, that's very bad.

**Comment by ijacquez** [comment]
Thanks for catching this. I'll add that.
