### ISSUE TITLE
sh2eb-elf-gcc.exe: error while loading shared libraries: libwinpthread-1.dll: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [ijacquez/libyaul#81]
Hey Yall, So Anyways After I Installed the SDK On Msys2, I was trying to compile one of the examples and when I typed make into the shell it gave me a error. the error says:
```
make: *** [/opt/tool-chains/sh2eb-elf/share/post.common.mk:187: /opt/yaul-examples/c++/build/@opt@yaul-examples@c++@c++.o] Error 127
```
so, idk what to do for the error so can you help me please!

**Comment by ijacquez** [comment]
Please paste the entire error. I'm unsure what error 127 is.

**Comment by NeoGeoFreak2004** [comment]
C:/msys64/opt/tool-chains/sh2eb-elf/bin/sh2eb-elf-gcc.exe: error while loading shared libraries: libwinpthread-1.dll: cannot open shared object file: No such file or directory
I think this is the error I am talking about.

**Comment by NeoGeoFreak2004** [comment]
well in simple terms, I used the installation guide for the existing msys2 shell and my operating system is windows 11 X64 bit.

**Comment by ijacquez** [comment]
I don't have access to Windows 11.

Could you search the Yaul installation to see if you have a `libwinpthread-1.dll` file?

**Comment by ijacquez** [comment]
I found a workaround.

First, install `mingw64/mingw-w64-x86_64-libwinpthread-git`:
```sh
pacman -S mingw64/mingw-w64-x86_64-libwinpthread-git
```
Then add
```sh
export PATH="/mingw64/bin:${PATH}"
```
to your `~/.bash_profile`.

This should fix your problem.
