### ISSUE TITLE
Build errors with examples/c++

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [ijacquez/libyaul#82]
Hey, So anyways i Just reinstalled msys2 and the libyaul toolchain but when i try to compile one of the sample programs it gives me a error, the error says:
```sh
make: *** [/opt/tool-chains/sh2eb-elf/share/post.common.mk:188: /opt/yaul-examples/c++/build/@opt@yaul-examples@c++@c++.o] Error 127
```
idk what this means so can you help me please!

**Comment by ijacquez** [comment]
Just as with the previous issue you opened, please provide the full output log, and use:
![image](https://user-images.githubusercontent.com/283713/152070847-cb00598a-42c0-4b7c-804e-30af5cf38f1b.png)
...to wrap the code, please.

**Comment by NeoGeoFreak2004** [comment]
"Executing "/opt/tool-chains/sh2eb-elf/share/update-cdb /usr/bin/gcc  /opt/yaul-examples/romdisk/romdisk.c  /opt/yaul-examples/romdisk/build/@opt@yaul-examples@romdisk@romdisk.o /opt/yaul-examples/romdisk/ compile_commands.json -W -Wall -Wextra -Werror -Wunused-parameter -Wstrict-aliasing -Wno-main -Wno-format -DHAVE_DEV_CARTRIDGE=1 -DHAVE_GDB_SUPPORT=0 -DHAVE_ASSERT_SUPPORT=1 -O2 -I. -save-temps=obj -isystem c:msys64opttool-chainssh2eb-elfbin../lib/gcc/sh2eb-elf/8.4.0/include -isystem c:msys64opttool-chainssh2eb-elfbin../lib/gcc/sh2eb-elf/8.4.0/include-fixed -isystem c:msys64opttool-chainssh2eb-elfbin../lib/gcc/sh2eb-elf/8.4.0/../../../../sh2eb-elf/sys-include -isystem c:msys64opttool-chainssh2eb-elfbin../lib/gcc/sh2eb-elf/8.4.0/../../../../sh2eb-elf/include -I. -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/bcl -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/tga -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/sega3d -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/common -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/dbgio -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/math -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/fs/fileclient -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/fs/romdisk -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/scu -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/scu/bus/a/cs0/dram-cart -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/scu/bus/a/cs0/usb-cart -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/scu/bus/a/cs2/cd-block -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/scu/bus/b/scsp -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/scu/bus/b/vdp -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/scu/bus/cpu -IC:/msys64/opt/tool-chains/sh2eb-elf/sh2eb-elf/include/yaul/scu/bus/cpu/smpc" failed
make: *** [/opt/tool-chains/sh2eb-elf/share/post.common.mk:184: /opt/yaul-examples/romdisk/build/@opt@yaul-examples@romdisk@romdisk.o] Error 127"
here is the full output when i type make into the msys shell.

**Comment by ijacquez** [comment]
Please install `gcc`:
```sh
pacman -Sy gcc
```
If that doesn't work, please edit your `.yaul.env` in `$HOME` and change the variable `YAUL_CDB` to `0`.

**Comment by NeoGeoFreak2004** [comment]
Thank You, The gcc install made it work!
