### ISSUE TITLE
Makefile creation Help

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [ijacquez/libyaul#83]
Hey, so anyways I just installed the libyaul toolchain on my pc and compiled some of the examples. And it is pretty great, however I have a big question, how do I create a Makefile so it can be compiled into a disc image format so I can make a backup and play it on my actual Sega Saturn.

**Comment by ijacquez** [comment]
If you were able to compile from start to finish any of the examples, then you've already created the `.cue` and `.iso`. The specifics on how to burn the file onto a CD-R is out of scope for the purpose of Yaul related issues. You can find other places that can explain the process in more detail. I also suggest you use an emulator.

Closing.
