### ISSUE TITLE
Black Screen on emulator help

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [ijacquez/libyaul#87]
Hey yall, so anyways i was watching the tutorial on writing Hello, World for the Sega Saturn using libyaul, but when i run the cue file on the yaubause emulator it goes to a black screen. IDK what to do so can you help me please!
Also I am using dbgio_printf btw!

**Comment by robertoduarte** [comment]
Hello, I think you forgot to load the Saturn BIOS on the emulador, some emulators run fine without the BIOS but it is not true for all games/applications.

**Comment by ijacquez** [comment]
> Hey yall, so anyways i was watching the tutorial on writing Hello, World for the Sega Saturn using libyaul, but when i run the cue file on the yaubause emulator it goes to a black screen. IDK what to do so can you help me please! Also I am using dbgio_printf btw!

As @robertoduarte mentioned, you do need a copy of the BIOS. I would try Mednafen as well.

If you found the video to be lacking in information regarding the setup for Mednafen, please let me know.
