### ISSUE TITLE
Makefile: add a variable to define realpath or readlink

### ISSUE THREAD

**Issue by shazz** [ijacquez/libyaul#9]
To avoid patching all the Makefiles each time, a variable to define to use realpath or readlink will be appreciated.

**Comment by ijacquez** [comment]
I can definitely do this. But in the long run, it will definitely go away when the VFS layer is implemented.

**Comment by ijacquez** [comment]
There are still issues involved with `realpath`/`readlink`

**Comment by ijacquez** [comment]
This should be much better. It's again, a temporary fix until VFS is actually implemented.
