### ISSUE TITLE
env file missing

### ISSUE THREAD

**Issue by WGR7** [ijacquez/libyaul#96]
Hi,

I've successfully built the compiler for an Ubuntu based Distro, but there's no .yaul.env file on /home/user/x-tools/sh2eb-elf/

What could be wrong?

**Comment by ijacquez** [comment]
I see that the instructions are not clear. Since you built the tool-chain manually, the file you need to copy is `.yaul.env.in`, which is located in the root of Yaul (this) repository.

I've updated the `README.md` file.

Let me know if this resolves the issue.

**Comment by ijacquez** [comment]
Closing as I haven't heard back.
